/* Generated By:JavaCC: Do not edit this line. indexConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface indexConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 19;
  /** RegularExpression Id. */
  int EXPONENT = 20;
  /** RegularExpression Id. */
  int DIGITS = 21;
  /** RegularExpression Id. */
  int PLURAL2 = 22;
  /** RegularExpression Id. */
  int EXCEPT = 23;
  /** RegularExpression Id. */
  int VERB = 24;
  /** RegularExpression Id. */
  int REPLACE = 25;
  /** RegularExpression Id. */
  int PLURAL = 26;
  /** RegularExpression Id. */
  int PAST = 27;
  /** RegularExpression Id. */
  int REPLACE2 = 28;
  /** RegularExpression Id. */
  int STOPPING = 29;
  /** RegularExpression Id. */
  int STRING = 30;
  /** RegularExpression Id. */
  int WORDS = 31;
  /** RegularExpression Id. */
  int VOWEL = 32;
  /** RegularExpression Id. */
  int NON_VOWEL = 33;
  /** RegularExpression Id. */
  int LETTER = 34;
  /** RegularExpression Id. */
  int OTHER = 42;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_HTML_TAG = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\" \"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"?\"",
    "\"!\"",
    "\"$\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"^\"",
    "\"@\"",
    "\"<<\"",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<DIGITS>",
    "<PLURAL2>",
    "<EXCEPT>",
    "<VERB>",
    "<REPLACE>",
    "<PLURAL>",
    "<PAST>",
    "<REPLACE2>",
    "<STOPPING>",
    "<STRING>",
    "<WORDS>",
    "<VOWEL>",
    "<NON_VOWEL>",
    "<LETTER>",
    "\"-\"",
    "\"/\"",
    "\"\\\\\"",
    "\"_\"",
    "\"<\"",
    "\">\"",
    "<token of kind 41>",
    "<OTHER>",
  };

}
